### ISSUE TITLE
Pre-release checklist

### ISSUE THREAD

**Issue by daemonspring** [ReactiveDrop/biogen-corporation#3]
# Check

- [ ] Translations (Any missing keys?)
- [ ] Lighting (Good lightmap grid scale? No weird dynamic lights?)
- [ ] Speedrun times
- [ ] AI navigation (good flow, marine hints)
- [ ] Soundscapes (Every transition area covered?)
- [ ] Naming (Is everything consistent? Are collisions avoided?)
- [ ] Removed redundant resources (Any unused materials?)
- [ ] Objective and campaign text
- [ ] Map overviews
- [ ] Credits
